### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by xDDoubleTea** [PoChieh-workplace/CurseofFight#3]
1. 鞘翅削弱
2. 武器庫鑰匙

**Comment by PoChieh-workplace** [comment]
[#a8381dee5610c328424e5e9d753f0089184c48b5
](https://github.com/PoChieh-workplace/CurseofFight/commit/a8381dee5610c328424e5e9d753f0089184c48b5)

changed the deep_dungeon key rate.

**Comment by PoChieh-workplace** [comment]
- 已將鞘翅削弱，附上耗損詛咒並取消耐久
[#5ae8f115a5b9a73658f883d5d99a4ae0ed821ace](https://github.com/PoChieh-workplace/CurseofFight/commit/5ae8f115a5b9a73658f883d5d99a4ae0ed821ace)
